// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBri09G-RYREXwMqMp0L9XMIHPtf8LeXsk',
    appId: '1:705279656030:web:f39cabc169dda8dc2134cf',
    messagingSenderId: '705279656030',
    projectId: 'cicd-marcos-dev',
    authDomain: 'cicd-marcos-dev.firebaseapp.com',
    storageBucket: 'cicd-marcos-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh8ZQj8McggHuTtEtkoQF4-DB2kuq624U',
    appId: '1:705279656030:android:c9c326e806c782be2134cf',
    messagingSenderId: '705279656030',
    projectId: 'cicd-marcos-dev',
    storageBucket: 'cicd-marcos-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs3DdCqSFmBhEvTIY-rA_FrgoFUP8STeI',
    appId: '1:705279656030:ios:d04c6843e6f255a62134cf',
    messagingSenderId: '705279656030',
    projectId: 'cicd-marcos-dev',
    storageBucket: 'cicd-marcos-dev.firebasestorage.app',
    iosBundleId: 'com.example.appCicd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs3DdCqSFmBhEvTIY-rA_FrgoFUP8STeI',
    appId: '1:705279656030:ios:d04c6843e6f255a62134cf',
    messagingSenderId: '705279656030',
    projectId: 'cicd-marcos-dev',
    storageBucket: 'cicd-marcos-dev.firebasestorage.app',
    iosBundleId: 'com.example.appCicd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBri09G-RYREXwMqMp0L9XMIHPtf8LeXsk',
    appId: '1:705279656030:web:0086253c5e504c132134cf',
    messagingSenderId: '705279656030',
    projectId: 'cicd-marcos-dev',
    authDomain: 'cicd-marcos-dev.firebaseapp.com',
    storageBucket: 'cicd-marcos-dev.firebasestorage.app',
  );
}
